spring:
  datasource:
    url: jdbc:h2:mem:btcsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false

  rabbitmq:
    listener:
      simple:
        auto-startup: false
      direct:
        auto-startup: false

#  PostgreSQL (production):
#  datasource:
#    url: jdbc:postgresql://localhost:5432/btcs
#    username: postgres
#    password: root