spring:
  application:
    name: btcs-edge

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/btcsedge}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

vaadin:
  launch-browser: true