-- V1: Initial schema – users, roles, permissions, and junction tables

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(200)
);

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(200)
);

CREATE TABLE users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                VARCHAR(120) NOT NULL UNIQUE,
    email                   VARCHAR(150) NOT NULL UNIQUE,
    password                VARCHAR(255) NOT NULL,
    first_name              VARCHAR(80),
    last_name               VARCHAR(80),
    user_role               VARCHAR(20),
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE,
    account_non_locked      BOOLEAN      NOT NULL DEFAULT TRUE,
    account_non_expired     BOOLEAN      NOT NULL DEFAULT TRUE,
    credentials_non_expired BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role       FOREIGN KEY (role_id)       REFERENCES roles (id)       ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE TABLE vehicle_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id UUID         NOT NULL UNIQUE,
    lane_no        SMALLINT     NOT NULL,
    direction      VARCHAR(10)  NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    plate_number   VARCHAR(20),
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE anpr_event (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_event_id BIGINT       NOT NULL,
    camera_id        VARCHAR(50)  NOT NULL,
    plate_number     VARCHAR(20),
    confidence       DOUBLE PRECISION,
    image_path       VARCHAR(500),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_anpr_vehicle_event FOREIGN KEY (vehicle_event_id) REFERENCES vehicle_event (id) ON DELETE CASCADE
);

CREATE TABLE weight_event (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_event_id BIGINT      NOT NULL,
    scale_id         VARCHAR(50) NOT NULL,
    weight_kg        INTEGER     NOT NULL,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_weight_vehicle_event FOREIGN KEY (vehicle_event_id) REFERENCES vehicle_event (id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  VARCHAR(40)  NOT NULL,
    user_id     BIGINT,
    username    VARCHAR(120) NOT NULL,
    ip          VARCHAR(64),
    user_agent  VARCHAR(255),
    success     BOOLEAN      NOT NULL,
    message     VARCHAR(500),
    path        VARCHAR(120),
    method      VARCHAR(10),
    created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_users_email         ON users (email);
CREATE INDEX idx_users_username      ON users (username);
CREATE INDEX idx_roles_name          ON roles (name);
CREATE INDEX ix_audit_created_at     ON audit_logs (created_at);
CREATE INDEX ix_audit_username       ON audit_logs (username);
CREATE INDEX ix_audit_user_id        ON audit_logs (user_id);
CREATE INDEX ix_audit_event_type     ON audit_logs (event_type);

